config/routes.rb
Rails.application.routes.draw do
  
  root to: "staticpages#index"
  resources :recipes

  get 'recipes', to: "recipes#recipes"

  get 'sobre', to: "staticpages#sobre"
  get 'contato', to: "staticpages#contato"
  

 get 'entrar', to: 'sessions#new', as: 'entrar'
 post 'entrar', to: 'sessions#create'
 get 'sair', to: 'sessions#destroy'
 get 'cadastro', to: 'users#new', as: 'cadastro' 
 get 'sessions/new'

resources :users

  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :recipes, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name, presence: true, length: { maximum: 50 }
  validates :recipe, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password
    before_save :email_downcase
  
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  
    validates :name, presence: true, length: { maximum: 50 }
    validates :password, length: { minimum: 6 }
    validates :email, presence: true, length: { maximum: 255 },
                                      format: { with: VALID_EMAIL_REGEX },
                                      uniqueness: { case_sensitive: true }

  has_many :recipes

  private

    def email_downcase
    self.email = email.downcase
    end
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: %i[ show edit update destroy ]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recipe_params
      params.require(:recipe).permit(:title, :description, :ingredients, :instructions)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to recipes_path(current_user) if user_signed_in?
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in(user)
      redirect_to recipes_path(current_user)
    else
      flash.now[:danger] = 'Email e Senha inválidos'
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:warning] = 'Logout realizado com sucesso'
    redirect_to cadastro_path
  end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

  def index
    @name = "indexhtml" 
  end

  def sobre

  end

  def contato
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_in_user, only: [:show, :edit, :update]

  def new
    redirect_to user_contacts_path(current_user) if user_signed_in?
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = 'Cadastro realizado com sucesso'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      flash[:success] = 'Dados atualizados com sucesso'
      redirect_to user_contacts_url(current_user)
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def sign_in(user)
      session[:user_id] = user.id
    end
  
      def sign_out
        session.delete(:user_id)
      end
  
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end
  
    def user_signed_in?
      !current_user.nil?
    end
  
  end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<section class="container p-3" id="footer">

<footer class="bg-gray text-black py-4 p-5" style=" box-shadow: 10px 20px 7px rgba(0, 0, 0, 0.2);">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h4>Informações de Contato</h4>

        <p>Email: exemplo@email.com</p>
        <p>Telefone: (123) 456-7890</p>
      </div>
      <div class="col-md-4">
        <h4>Links Rápidos</h4>
        <ul class="list-unstyled text-danger">
          <li><a href="index.html" class="text-danger">Página Inicial</a></li>
          <li><a href="#quemsomos" class="text-danger">Receitas</a></li>
          <li><a href="#" class="text-danger">Sobre</a></li>
          <li><a href="#" class="text-danger">Contato</a></li>
        </ul>
      </div>
      <div class="col-md-4">
        <h4>Redes Sociais</h4>
        <a href="https://www.instagram.com/devsync.tech/" class="btn btn-outline-danger btn-social ">
          <i class="bi bi-instagram"></i>
        </a>
        <a href="#" class="btn btn-outline-danger btn-social">
          <i class="bi bi-facebook"></i>
        </a>
        <a href="#" class="btn btn-outline-danger btn-social">
          <i class="bi bi-whatsapp"></i>
        </a>

      </div>
    </div>
  </div>
</footer>
</section>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    

app/views/layouts/_header.html.erb
<div class="bg-danger">
<h6 class="text-light text-center">
 <i class="p-1">Descubra um mundo de sabores, todas as suas receitas em um só lugar!  </i>
</h6>
</div>

<main class="container text-center">

<div class="navbar-fixa">
<nav class="navbar bg-muted navbar-expand-lg" style=" box-shadow: 5px 10px 7px rgba(0, 0, 0, 0.2);">
  <div class="container-fluid">

  
    <a class="navbar-brand" href="#">
    <%= image_tag("logo.png", style: "max-width: 70px; max-height: 180px;") %>
    </a>

      <%= link_to 'Home', root_path, class: 'black-link text-decoration-none text-md-start p-1 ' %>
    
        <%= link_to 'Sobre', sobre_path, class: 'black-link text-decoration-none p-1' %>
   
        <%= link_to 'Contato', contato_path, class: 'black-link text-decoration-none p-1'  %>
        <% if !user_signed_in? %>

        <%= link_to 'Entrar', entrar_path, class: 'btn btn-danger' %>
       
      <% if !user_signed_in? %>
    
        <%= link_to 'Nova Conta', cadastro_path, class: 'btn btn-outline-danger' %>
       <% end %>
       
        <% else %>


  <div id="espaco">
  
  </div>
  <div class="dropdown">
  <button class="btn btn-danger dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
  bem vindo, <%= current_user.name %> <span class="caret"></span>
  </button>

  <ul class="dropdown-menu dropdown-menu border border-danger p-1">
    <li>
    <%= link_to 'Receitas', recipes_path(current_user), class: 'text-primary text-decoration-none' %>
    </li>
    <li>
    <%= link_to 'Editar', edit_user_path(current_user), class: 'text-primary text-decoration-none' %>
    </li>
    <li>
    <%= link_to 'Sair', sair_path, method: :delete %>
    </li>
  </ul>
</div>
<% end %>       
  </div>
</nav>
</div>

<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/css/bootstrap.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookreceitas</title>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag 'style', 'data-turbo-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag 'favi.ico' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  
  <% flash.each do |message_type, message| %>
    <%= content_tag 'div', class: "alert alert-danger   alert alert-#{message_type} alert-dismissible", role: 'alert' do %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <%= message %>
    <% end %>
  <% end %>

  
  <%= yield %>
  
  <%= render 'layouts/footer' %>

  
    </body>  
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "mt-4") do |form| %>
  <% if recipe.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(recipe.errors.count, "error") %> impediram que esta receita fosse salva:</h2>

      <ul>
        <% recipe.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<br>
  <div class="form-group text-md-start">
    <%= form.label :Nome %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group text-md-start">
    <%= form.label :descrição %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group text-md-start">
    <%= form.label :ingredientes %>
    <%= form.text_area :ingredients, class: "form-control" %>
  </div>

  <div class="form-group text-md-start">
    <%= form.label :instruções %>
    <%= form.text_area :instructions, class: "form-control" %>
  </div>

  <div class="form-group text-center">
    <%= form.submit "Salvar Alterações", class: "btn btn-primary" %>
  </div>

<% end %>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    

app/views/recipes/_recipe.html.erb
<div class="container p-1" id="<%= dom_id(recipe) %>">
  <p class="text-justify mb-0">
  <p style="font-size: 45px; color: #red; line-height: 1.5;  font-family: 'Merienda', sans-serif;">
  <%= recipe.title %>
  </p>
</p>
  </p>

  <p class="text-justify">
  <p class="text-danger h5 text-justify">
    <strong>Descrição:</strong>
    </p>
    <%= recipe.description %>
  </p>

  <p class="text-justify">
  <p class="text-danger h5 text-justify">
    <strong>Igredientes:</strong>
    </p>
    <%= recipe.ingredients %>
  </p>

  <p class="text-justify">
  <p class="text-danger h5 text-justify">
    <strong>Instruções:</strong>
    </p>
    <%= recipe.instructions %>
  </p>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Voltar para Receita", @recipe %> |
  <%= link_to "Voltar", recipes_path %>
</div>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

app/views/recipes/index.html.erb
<section class="container p-1">
<p style="color: green"><%= notice %></p>

<h1 class="text-danger title">Minhas Receitas</h1>
<h1> Olá <%= current_user.name %> </h1>
<div id="recipes" class="text-md-start">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
    <p>
      <%= link_to "Ver esta Receita", recipe, class: 'btn btn-outline-danger' %>
      </p>
  <% end %>
  <center>
  <%= link_to "Nova Receita", new_recipe_path, class: 'btn btn-outline-success btn-lg text-center' %>
  </center>
  </div>
</section>

app/views/recipes/new.html.erb
<h1 class="text-danger title p-3">Nova Receita</h1>
<%= render "form", recipe: @recipe %>

<div>
  <%= link_to "Voltar as Receitas", recipes_path %>
</div>

app/views/recipes/show.html.erb
<section class="container p-1">
<p style="color: green"><%= notice %></p>

<%= render @recipe %>

<div class="container p-1 text-center row">
  <%= link_to "Editar Receita", edit_recipe_path(@recipe), class: 'btn btn-outline-primary p-1' %> 
  <%= link_to "Voltar para Receitas", recipes_path,  class: 'btn btn-outline-success p-1'  %>
  <%= button_to "Excluir", @recipe, method: :delete, class: 'btn btn-outline-danger p-1' %>
</div>
</section>

app/views/staticpages/contato.html.erb
<h1> Contato </h1>

app/views/staticpages/index.html.erb
<main class="container text-center p-1">
  <section id="home" class="container my-4 p-4 ">
    <div class="row">
      <div class="col-12 col-lg-6 pt-5">
        <br>
        <h1 id="bem-vindo" class="text-danger text-center p-1 display-4">Bem Vindo(a) ao BookReceitas</h1>
        <p class="text-center h6"> <i> Um mundo de sabores, todas as suas receitas em um só app!</i></p>
        <div class="mt-5">
       
        <button class="btn btn-danger text-center p-1 text-white text-md-start">

        <p class="h2">
        <%= link_to 'Começar', recipes_path, class: 'white-link' %>
        </p>
        </div>
      </div>

      <div class="col-12 col-lg-6">
        <img id="rocket" src="/assets/recipe.svg" width="400px" height="400px" alt="" srcset="">
      </div>

      <img src="/static/img/rocket.png" alt="" srcset="">

    </div>
  </section>

  <div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-4">
    <div class="text-white text-center p-3 d-lg-block none">
    <img id="rocket2" src="/assets/recipe2.svg" class="img-fluid none" alt="" srcset="">
    </div>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <p class="card-text p-3 ">Bem-vindo ao BookReceitas, sua nova plataforma favorita para guardar e organizar suas receitas de forma eficaz e prática.
<p>
        Com o BookReceitas, você não apenas armazena suas receitas, mas também as organiza de maneira inteligente para que você possa encontrá-las facilmente quando precisar. Quer esteja buscando uma receita para um jantar especial, uma opção saudável para a semana, ou apenas explorando novas ideias culinárias, nós temos tudo o que você precisa.</i>
        </p>
        <p class="card-text"><small class="text-body-secondary"><i>Vamos começar?</i></small></p>
      </div>
    </div>
  </div>
</div>


<div class="card">
  <div class="card-header">
    
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>Se você é o que você come, então eu só quero comer as coisas boas.</p>
      <footer class="blockquote-footer">Frase famosa de <cite title="Source Title">Ratatouille (Filme)</cite></footer>
    </blockquote>
  </div>
</div>

app/views/staticpages/sobre.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sobre Mim</title>
  <!-- Adicionando Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <style>
    /* Estilos adicionais podem ser adicionados aqui */
    .about-me-section {
      padding: 50px 0;
      background-color: #f8f9fa;
    }
  </style>
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2">
        <div class="about-me-section text-center">
          <h2 class="mb-4">Sobre Mim</h2>
          <img src="https://via.placeholder.com/150" alt="Minha Foto" class="img-fluid rounded-circle mb-4">
          <p class="lead">Olá, eu sou [Seu Nome]! Desenvolvedor apaixonado por tecnologia, com experiência em [suas habilidades].</p>
          <p>Meu objetivo é [objetivo pessoal/profissional].</p>
          <p>Além de programar, gosto de [seus hobbies/interesses].</p>
          <p>Fique à vontade para entrar em contato comigo através do meu e-mail: [seu e-mail] ou me seguir nas redes sociais.</p>
          <div class="social-links mt-4">
            <!-- Adicione links para suas redes sociais aqui -->
            <a href="#" class="btn btn-primary btn-lg mr-2">Twitter</a>
            <a href="#" class="btn btn-primary btn-lg mr-2">LinkedIn</a>
            <a href="#" class="btn btn-primary btn-lg">GitHub <i class="bi bi-github"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  <!-- Adicionando Bootstrap JS (opcional, se você precisar de funcionalidades como o navbar collapse) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/users/_fields.html.erb
<div class="form-group text-md-start">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

<div class="form-group text-md-start">
  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>
</div>

<div class="form-group  text-md-start ">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>

<div class="form-group  text-md-start">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Cadastrar-se</h1>
  </div>

  <div class="container">

  <%= form_for @user do |f| %>
      <%= render 'fields', f: f %>

      <%= f.submit 'Cadastrar', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1> Olá <%= current_user.name %>, qual vai ser a receita de hoje? </h1>